# Generated by Django 4.1 on 2022-11-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата запроса к геокодеру'),
        ),
    ]
