# Generated by Django 4.1 on 2022-08-18 18:49

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0037_auto_20210125_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='имя')),
                ('lastname', models.CharField(db_index=True, max_length=50, verbose_name='фамилия')),
                ('address', models.CharField(max_length=200, verbose_name='адрес')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=20, region=None, verbose_name='телефон')),
                ('products', models.ManyToManyField(related_name='orders', to='foodcartapp.product', verbose_name='позиции в заказе')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
    ]
