# Generated by Django 4.1 on 2022-10-13 09:22

from django.db import migrations


class Migration(migrations.Migration):
    
    def fill_orderitem_price(apps, schema_editor):
        OrderItem = apps.get_model("foodcartapp", "OrderItem")
        order_items = OrderItem.objects.all()
        for order_item in order_items.iterator():
            order_item.price = order_item.product.price
            order_item.save()

    dependencies = [
        ('foodcartapp', '0041_alter_orderitem_order_alter_orderitem_product'),
    ]

    operations = [
        migrations.RunPython(fill_orderitem_price),
    ]
