# Generated by Django 4.1 on 2022-10-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_orderitem_price_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('PROCESS', 'В обработке'), ('DELIVERED', 'Доставлен')], db_index=True, default='NEW', max_length=9, verbose_name='статус'),
        ),
    ]
